Fix the property `disturbance`
ternaustralia/dawe-rlp-vocabs pull request #224
Opened 2022-09-08 04:40 UTC by junrongYu

Fixes: #71

2022-09-08 04:40 UTC, junrongYu commented
The source, definition, and feature type need to be confirmed.

2022-09-09 03:10 UTC, edmondchuc commented
> The source, definition, and feature type need to be confirmed.

I'm guessing this is not ready to be reviewed yet then?

Also, shouldn't there be 2 disturbance properties deleted, not just one? The original issue states there are 3 in total.

2022-09-09 03:18 UTC, junrongYu commented
> > The source, definition, and feature type need to be confirmed.
> 
> I'm guessing this is not ready to be reviewed yet then?
> 
> Also, shouldn't there be 2 disturbance properties deleted, not just one? The original issue states there are 3 in total.

Hi @edmondchuc , those 2 `disturbance` in the issue are actually the same property with different definitions, so I was asking for the correct definition then. @arunherb said he'll review definitions later.

2022-09-12 03:30 UTC, junrongYu commented
The feature type is `land surface disturbance`.

2022-09-13 05:44 UTC, edmondchuc requested changes

2022-09-13 05:44 UTC, edmondchuc commented on vocab_files/observable_property_concepts/disturbance.ttl
>      skos:prefLabel "disturbance" ;
This observable property is about the disturbance type found at a site.

```suggestion
    skos:prefLabel "disturbance type" ;
```

2022-09-13 05:44 UTC, edmondchuc commented on vocab_files/observable_property_concepts/disturbance.ttl
> +    skos:altLabel "land surface disturbance" ;
I don't think having `land surface disturbance` as an alternative label makes sense. You're basically saying all instances of disturbance type is some kind of land surface disturbance, which is not true. Land surface is a specific type of survey (see Yellow Book) and disturbances can happen in many different types of surveys (e.g., vegetation, soil).

2022-09-13 06:10 UTC, edmondchuc approved these changes

2022-09-14 01:49 UTC, merged