Fixed the CV issues from the Workshop on Set-1 for version-2
ternaustralia/dawe-rlp-vocabs pull request #561
Opened 2024-05-20 03:20 UTC by arunherb

Workshop for set-1 controlled vocabularies have been updated.

2024-05-20 05:07 UTC, junrongYu commented
Hi @arunherb , for the `land-use history` update, can you please remove the attribute concept file & move the LUT URI to metadata file, update the value type in metadata to `tern:IRI`? Can you please also state the changes in commit message?

2024-05-20 05:34 UTC, junrongYu requested changes

2024-05-20 05:34 UTC, junrongYu commented on vocab_files/observable_properties_by_module/plot-description/plot-description-enhanced-protocol/land-use-history.ttl
> +    tern:hasCategoricalCollection <http://www.neii.gov.au/def/voc/ACLUMP/australian-land-use-and-management-classification/Australian-Land-Use-and-Management-Classification> ;
```suggestion
    urnp:categoricalValuesCollection <http://www.neii.gov.au/def/voc/ACLUMP/australian-land-use-and-management-classification/Australian-Land-Use-and-Management-Classification> ;
```

2024-05-20 05:46 UTC, junrongYu approved these changes

2024-05-21 02:08 UTC, junrongYu commented
Hi @arunherb , for this update `Remove OP species identification status and its metadata files in ` floristics - standard``, can you please bring the concept file back cuz it may be used in set2/3, and remove its URI form the OPs collection file of `floristics - standard`. Thanks!

2024-05-21 02:17 UTC, junrongYu commented
Hi @arunherb , same here, for `Remove OPs field species name and growth form and their metadata files in cover-standard`, can you please remove the URIs of OPs `field species name` and `growth form` from the OP collection file in `cover - standard`. Thanks!

2024-05-21 02:57 UTC, junrongYu commented
Hi @arunherb , for this update 'Rename OP fractional cover responses to fractional cover types, in concept file, metadata file;', can you please remove the extra `v` in file url, it's `vvocabs_file`. Thanks!

2024-05-21 03:03 UTC, arunherb commented
> Hi @arunherb , for this update 'Rename OP fractional cover responses to fractional cover types, in concept file, metadata file;', can you please remove the extra `v` in file url, it's `vvocabs_file`. Thanks!

Done

2024-05-21 03:06 UTC, arunherb commented
> Hi @arunherb , same here, for `Remove OPs field species name and growth form and their metadata files in cover-standard`, can you please remove the URIs of OPs `field species name` and `growth form` from the OP collection file in `cover - standard`. Thanks!

Done

2024-05-21 04:02 UTC, junrongYu commented
Hi @arunherb , for `floristics - standard`, you've added the metadata URI of `dead branch` to the collection file, should be the concept URI, can you please correct it? Thanks!

2024-05-21 04:30 UTC, arunherb commented
> Hi @arunherb , for `floristics - standard`, you've added the metadata URI of `dead branch` to the collection file, should be the concept URI, can you please correct it? Thanks!

This is probably 'cover - standard'; It has been updated. Thanks

2024-05-21 07:38 UTC, junrongYu commented
Hi @arunherb , thanks for the update, can you please fix these:
1. for the 'Remove attribute land-use history;Add OP land-use history and its metadata file, feature type is land surface', feature type is `land surface`;
2. for the 'Remove attribute source of identification and its relationship with OP field species name', can you please bring the concept file back, it's used un set2;
3. for the metadata file of OP `animal count`, should the feature type be `animal occurrence`?
4. for both `animal count` and `plant count`, can you please add those attributes linked with `number of individuals` with those 2 new OPs in metadata? they are observation method tier1/2/3, and observation notes
Thanks!

2024-05-21 22:54 UTC, arunherb commented
> Hi @arunherb , thanks for the update, can you please fix these:
> 
> 1. for the 'Remove attribute land-use history;Add OP land-use history and its metadata file, feature type is land surface', feature type is `land surface`; **(DONE)**
> 2. for the 'Remove attribute source of identification and its relationship with OP field species name', can you please bring the concept file back, it's used un set2; **(DONE)**
> 3. for the metadata file of OP `animal count`, should the feature type be `animal occurrence`?**(DONE)**
> 4. for both `animal count` and `plant count`, can you please add those attributes linked with `number of individuals` with those 2 new OPs in metadata? they are observation method tier1/2/3, and observation notes - I think we decided not to have this concept 'number of individuals', instead I have renamed this to 'indivdiual count' and linked it to animal and plant count as a broader concept. _For the second part 'observation method tier 1/2/3' I need more clarity as to what needs to be added where._
Thanks!

2024-05-21 23:36 UTC, junrongYu commented
> > Hi @arunherb , thanks for the update, can you please fix these:
> > 
> > 1. for the 'Remove attribute land-use history;Add OP land-use history and its metadata file, feature type is land surface', feature type is `land surface`; **(DONE)**
> > 2. for the 'Remove attribute source of identification and its relationship with OP field species name', can you please bring the concept file back, it's used un set2; **(DONE)**
> > 3. for the metadata file of OP `animal count`, should the feature type be `animal occurrence`?**(DONE)**
> > 4. for both `animal count` and `plant count`, can you please add those attributes linked with `number of individuals` with those 2 new OPs in metadata? they are observation method tier1/2/3, and observation notes - I think we decided not to have this concept 'number of individuals', instead I have renamed this to 'indivdiual count' and linked it to animal and plant count as a broader concept. _For the second part 'observation method tier 1/2/3' I need more clarity as to what needs to be added where._
> >    Thanks!

Hi @arunherb , yes we removed the `number of individuals`, replaced it with `animal count` / `plant count`, this is definitely correct. However, when removed its metadata file, we lost the relationship between this OP and its attributes. Attributes `observation method tier 1/2/3` and `observation notes` are attributes of all OPs in `opportune` module.

2024-05-22 04:12 UTC, junrongYu approved these changes

2024-05-22 04:22 UTC, merged